# Copyright (C) 2026 YuzakiKokuban <heibanbaize@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-only

moduledir = "/data/adb/modules"
mountsource = "KSU"
overlay_mode = "ext4"
disable_umount = false
default_mode = "overlay"
custom_mounts = []
rules = {}

[kasumi]
enabled = false
lkm_autoload = true
lkm_dir = "/data/adb/modules/hybrid_mount/kasumi_lkm"
lkm_kmi_override = ""
mirror_path = "/dev/kasumi_mirror"
enable_kernel_debug = false
enable_stealth = false
enable_overlay_xattr_hide = false
enable_selinux_fix = false
enable_mount_hide = false
enable_maps_spoof = false
enable_statfs_spoof = false
hide_uids = []
uname_mode = "scoped"
cmdline_value = ""
kstat_rules = []
maps_rules = []

[kasumi.mount_hide]
enabled = false
path_pattern = ""

[kasumi.statfs_spoof]
enabled = false
path = ""
spoof_f_type = 0

[kasumi.uname]
sysname = ""
nodename = ""
release = ""
version = ""
machine = ""
domainname = ""
