/*
 * Copyright (C) 2026 YuzakiKokuban <heibanbaize@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by webui/scripts/generate-daemon-protocol.mjs from src/core/daemon/protocol.rs.
// Do not edit by hand.

export const DAEMON_COMMAND_TYPES = [
  "api-config-get",
  "api-config-patch",
  "api-config-reset",
  "api-config-set",
  "api-kasumi-maps-add",
  "api-kasumi-maps-clear",
  "api-kernel-uname",
  "api-modules-apply",
  "api-modules-list",
  "api-mount-stats",
  "api-mount-topology",
  "api-open-url",
  "api-partitions",
  "api-reboot",
  "api-storage",
  "api-system-info",
  "api-version",
  "hide-add",
  "hide-apply",
  "hide-list",
  "hide-remove",
  "init",
  "kasumi-apply-config-runtime",
  "kasumi-clear",
  "kasumi-clear-uname",
  "kasumi-features",
  "kasumi-fix-mounts",
  "kasumi-hooks",
  "kasumi-invalidate-cache",
  "kasumi-list",
  "kasumi-release-connection",
  "kasumi-restore-uname-global",
  "kasumi-rule-add",
  "kasumi-rule-add-dir",
  "kasumi-rule-delete",
  "kasumi-rule-hide",
  "kasumi-rule-merge",
  "kasumi-rule-remove-dir",
  "kasumi-set-uname",
  "kasumi-status",
  "kasumi-version",
  "lkm-load",
  "lkm-status",
  "lkm-unload",
  "ping",
  "shutdown",
  "status",
  "webui-start",
] as const;

export type DaemonCommandType = (typeof DAEMON_COMMAND_TYPES)[number];
